Made installation notes clearer

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -139,8 +139,9 @@ if [ "$HAS_ELINKS" -eq "0" ];
 then
   log_end "found" 1>&2
 else
-  log_end "not found; make sure it's in PATH" 1>&2
-  exit 1
+  log_end "${COLOR_RED}not found${COLOR_OFF}; make sure it's in PATH" 1>&2
+  log "${COLOR_RED}Error: ${COLOR_OFF}manual generation will not work"
+  log "${COLOR_RED}Note: ${COLOR_OFF}normal install of reference pages will still work."
 fi
 
 # Configure the makefile
@@ -154,3 +155,5 @@ sed "s#%TMP_MAN%#${TMP_MAN}#" ./Makefile.tmp2 > ./Makefile.tmp1
 sed "s#%THREADS%#${THREADS}#" ./Makefile.tmp1 > ./Makefile
 
 log "Done configuring ${PROJECT}"
+log
+log "To install, use \`sudo make install\`"
