Now verifies gzip existence

diff --git a/do_generate b/do_generate
--- a/do_generate
+++ b/do_generate
@@ -10,20 +10,27 @@
 # XXX: Do not call this script directly: use `make generate`
 set -o nounset
 
-# elinks
+# colors
 color_off=$(tput sgr0)
 color_red=$(tput setaf 1)
-printf "$echo_prefix Checking for elinks... "
-which elinks > /dev/null 2>&1
-HAS_ELINKS=$?
-if [ "$HAS_ELINKS" -eq "0" ];
-then
-  echo "found" 1>&2
-else
-  echo "${color_red}not found${color_off}; make sure it's in PATH" 1>&2
-  echo "${color_red}Error: ${color_off}manual generation will not work"
-  exit 1
-fi
+
+function check_existence 
+{
+  printf "$echo_prefix Checking for $1... "
+  which $1 > /dev/null 2>&1
+  exists=$?
+  if [ "$exists" -eq "0" ];
+  then
+    echo "found" 1>&2
+  else
+    echo "${color_red}not found${color_off}; make sure it's in PATH" 1>&2
+    echo "${color_red}Error: ${color_off}manual generation will not work"
+    exit 1
+  fi
+}
+
+check_existence "elinks"
+check_existence "gzip"
 
 echo "$echo_prefix Generating from $reference to $tmp_man"
 echo "  $echo_prefix Removing previous files"
