Install should be more portable now

diff --git a/do_generate b/do_generate
--- a/do_generate
+++ b/do_generate
@@ -10,21 +10,17 @@
 # XXX: Do not call this script directly: use `make generate`
 set -o nounset
 
-# colors
-color_off=$(tput sgr0)
-color_red=$(tput setaf 1)
-
 function check_existence 
 {
-  printf "$echo_prefix Checking for $1... "
+  printf "Checking for $1... "
   which $1 > /dev/null 2>&1
   exists=$?
   if [ "$exists" -eq "0" ];
   then
     echo "found" 1>&2
   else
-    echo "${color_red}not found${color_off}; make sure it's in PATH" 1>&2
-    echo "${color_red}Error: ${color_off}manual generation will not work"
+    echo "not found; make sure it's in PATH" 1>&2
+    echo "Error: manual generation will not work"
     exit 1
   fi
 }
@@ -32,18 +28,18 @@ function check_existence
 check_existence "elinks"
 check_existence "gzip"
 
-echo "$echo_prefix Generating from $reference to $tmp_man"
-echo "  $echo_prefix Removing previous files"
+echo "Generating from $reference to $tmp_man"
+echo "  Removing previous files"
 rm -f $tmp_man/*.3
-echo "  $echo_prefix Parsing documentation on $threads threads"
+echo "  Parsing documentation on $threads threads"
 find $reference -name '*.html' -print0 | xargs -0 -n 1 -P $threads -I % \
 ./bin/stdman -d $tmp_man % > /dev/null 2>&1
 
-echo "  $echo_prefix Removing unwanted pages"
+echo "  Removing unwanted pages"
 for file in $(find $tmp_man -name '*.3' | grep -v "std::") ; do
   rm -f $file;
 done
 
-echo "  $echo_prefix Creating links for common typedefs"
+echo "  Creating links for common typedefs"
 ./do_link
-echo "$echo_prefix Done generating"
+echo "Done generating"
